---
title: Fn4 Build on OCI
description: Deployment of base Fn4 on OCI
schemaVersion: 1.1.0
version: "20210315"
logoUrl: >
  https://objectstorage.uk-london-1.oraclecloud.com/p/gcJUrJ8giUwk_51hi_nTN0Dl66R_7jOOAXU3k3kF-4mOrDCwIoanxChzle0ZAIfm/n/lrbvkel2wjot/b/images/o/mmmlogo_small_130_130.png
locale: "en"
variableGroups:
  - title: "Base configuration"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${ssh_pub_key}
      - ${env_name}
      - ${specify_prefix}
      - ${name_prefix}
  - title: "Bastion Config"
    variables:
      - ${bastion_image}
      - ${bastion_shape}
      - ${bastion_ocpus}
      - ${bastion_ram}
  - title: "App Server Config"
    variables:
      - ${appsrv_count}
      - ${appsrv_image}
      - ${appsrv_shape}
      - ${appsrv_ocpus}
      - ${appsrv_ram}
  - title: "DB Server Config"
    variables:
      - ${dbsrv_count}
      - ${dbsrv_image}
      - ${dbsrv_shape}
      - ${dbsrv_ocpus}
      - ${dbsrv_ram}
      - ${clone_db_backup}
      - ${dbsrv_src_backup_vol_id}
  - title: "Optional Settings"
    variables:
      - ${appsrv_boot_size}
      - ${dbsrv_boot_size}
      - ${create_child_comp}
      - ${create_dns}
      - ${show_testing_others}
  - title: "Testing / Other Settings"
    variables:
      - ${bastion_boot_size}
      - ${deploy_test}
    visible: ${show_testing_others}
variables:
  tenancy_ocid:
    visible: false
  region:
    title: "Region"
    type: oci:identity:region:name
  compartment_ocid:
    title: "Target Compartment"
    type: oci:identity:compartment:id
    required: true
  ssh_pub_key:
    type: oci:core:ssh:publickey
    title: "Public SSH key"
    required: true
    additionalProps:
      allowMultiple: true
  bastion_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Canonical Ubuntu"
      operatingSystemVersion: "20.04"
    required: true
    description: "Compute image for the Bastion server"
    title: "Bastion Server Image"
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${bastion_image}
    required: true
    description: "Compute shape for the Bastion server"
    title: "Bastion Server Shape"
  bastion_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "Bastion number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
            - bastion_shape
            - "VM.Standard.E3.Flex"
  bastion_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "Bastion Server memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
            - bastion_shape
            - "VM.Standard.E3.Flex"
  appsrv_count:
    type: integer
    minimum: 1
    maximum: 16
    default: 1
    required: true
    title: "App server(s) to deploy"
    description: "The number of combined App server(s) that will be deployed"
    visible: false
  appsrv_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Canonical Ubuntu"
      operatingSystemVersion: "20.04"
    required: true
    description: "Compute image for the App server(s)"
    title: "App Server Image"
  appsrv_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${headnode_image}
    required: true
    description: "Compute shape for the App server(s)"
    title: "App Server Shape"
  appsrv_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "App server(s) number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
            - appsrv_shape
            - "VM.Standard.E3.Flex"
  appsrv_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "App server(s) memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
            - appsrv_shape
            - "VM.Standard.E3.Flex"
  dbsrv_count:
    type: integer
    minimum: 1
    maximum: 16
    required: true
    title: "DB server(s) to deploy"
    description: "The number of combined DB server(s) that will be deployed"
  dbsrv_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Canonical Ubuntu"
      operatingSystemVersion: "20.04"
    required: true
    description: "Compute image for the DB server(s)"
    title: "DB Server Image"
  dbsrv_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${headnode_image}
    required: true
    description: "Compute shape for the DB server(s)"
    title: "DB Server Shape"
  dbsrv_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "DB server(s) number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
            - dbsrv_shape
            - "VM.Standard.E3.Flex"
  dbsrv_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "DB server(s) memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
            - dbsrv_shape
            - "VM.Standard.E3.Flex"
  clone_db_backup:
    type: boolean
    title: "Specify backup volume to clone and attach to the first DB server?"
    default: true
    required: true
    description: "Specify backup volume to clone and attach to the first DB server?"
  dbsrv_src_backup_vol_id:
    type: string
    title: "Volume ID to be cloned"
    required: true
    visible: ${clone_db_backup}
    description: "The OCID of the Block Volume that should be cloned and attached to the first DB instance - e.g. ocid1.volume.oc1.uk-london-1.<a-z0-9>"
  env_name:
    type: string
    title: "Environment Name"
    description: "Name for the environment - e.g. fn4 - lower case and digits only - must start with lower case letter"
    pattern: "^[a-z][a-z0-9]+$"
    default: "fn4"
    required: true
  specify_prefix:
    title: "Would you like to specify a prefix for the deployment?"
    type: boolean
    default: false
  name_prefix:
    type: string
    title: "Display/Host Name Prefix"
    description: "Optional prefix for all Display Names and Hostnames - lower case and digits only - must start with lower case letter"
    pattern: "^[a-z][a-z0-9]+$"
    visible: ${specify_prefix}
  appsrv_boot_size:
    type: integer
    title: "App Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  dbsrv_boot_size:
    type: integer
    title: "DB Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  create_child_comp:
    title: "Create a child compartment for the stack"
    type: boolean
    default: true
  create_dns:
    title: "Create DNS record in oci.fn4dev.ml?"
    type: boolean
    default: true
  show_testing_others:
    title: "Display all other settings / testing options?"
    type: boolean
    default: false
  bastion_boot_size:
    type: integer
    title: "Bastion Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  deploy_test:
    visible: false
outputs:
  Fn4_bastion:
    title: "Bastion DNS / Public IP Address"
    type: copyableString
    visible: true
  Fn4App_DB_SrvPrivateIP:
    title: "App/DB Private IP Address"
    type: copyableString
    visible: true
  Fn4_deploy_id:
    title: "Deployment ID"
    type: string
    visible: true
