---
title: Fn4 Build on OCI
description: Deployment of base Fn4 on OCI
schemaVersion: 1.1.0
version: "20210315"
logoUrl: >
  https://objectstorage.uk-london-1.oraclecloud.com/p/gcJUrJ8giUwk_51hi_nTN0Dl66R_7jOOAXU3k3kF-4mOrDCwIoanxChzle0ZAIfm/n/lrbvkel2wjot/b/images/o/mmmlogo_small_130_130.png
locale: "en"
variableGroups:
  - title: "Base configuration"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${randomise_ad}
      - ${ad}
      - ${ssh_pub_key}
      - ${env_name}
      - ${specify_prefix}
      - ${name_prefix}
  - title: "Bastion Config"
    variables:
      - ${bastion_image}
      - ${bastion_shape}
      - ${bastion_ocpus}
      - ${bastion_ram}
  - title: "App/DB Server Config"
    variables:
      - ${appdbsrv_count}
      - ${appdbsrv_image}
      - ${appdbsrv_shape}
      - ${appdbsrv_ocpus}
      - ${appdbsrv_ram}
  - title: "Optional Settings"
    variables:
      - ${appdb_boot_size}
      - ${appdb_backup_size}
      - ${create_child_comp}
      - ${install_certs}
      - ${create_dns}
      - ${show_testing_others}
  - title: "Testing / Other Settings"
    variables:
      - ${bastion_boot_size}
      - ${deploy_test}
    visible: ${show_testing_others}
variables:
  tenancy_ocid:
    visible: false
  region:
    title: "Region"
    type: oci:identity:region:name
  compartment_ocid:
    title: "Target Compartment"
    type: oci:identity:compartment:id
    required: true
  randomise_ad:
    type: boolean
    title: "Select random Availability Domain for cluster"
    description: "All nodes for this cluster and the Bastion will be placed in the same, randomly selected AD."
    default: true
  ad:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: ${compartment_ocid}
    required: true
    description: "Availability Domain"
    title: "Availability Domain"
    visible:
      not:
        - ${randomise_ad}
  ssh_pub_key:
    type: oci:core:ssh:publickey
    title: "Public SSH key"
    required: true
    additionalProps:
      allowMultiple: true
  bastion_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Canonical Ubuntu"
      operatingSystemVersion: "18.04"
    required: true
    description: "Compute image for the Bastion server"
    title: "Bastion Server Image"
  bastion_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${bastion_image}
    required: true
    description: "Compute shape for the Bastion server"
    title: "Bastion Server Shape"
  bastion_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "Bastion number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
            - bastion_shape
            - "VM.Standard.E3.Flex"
  bastion_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "Bastion Server memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
            - bastion_shape
            - "VM.Standard.E3.Flex"
  appdbsrv_count:
    type: integer
    minimum: 1
    maximum: 16
    required: true
    title: "Combined App/DB server(s) to deploy"
    description: "The number of combined App / DB servers that will be deployed"
  appdbsrv_image:
    type: oci:core:image:id
    dependsOn:
      compartmentId: ${compartment_ocid}
      operatingSystem: "Canonical Ubuntu"
      operatingSystemVersion: "18.04"
    required: true
    description: "Compute image for the App / DB server"
    title: "App / DB Server Image"
  appdbsrv_shape:
    type: oci:core:instanceshape:name
    dependsOn:
      compartmentId: ${compartment_ocid}
      imageID: ${headnode_image}
    required: true
    description: "Compute shape for the App / DB"
    title: "App / DB Server Shape"
  appdbsrv_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    required: true
    title: "App / DB number of CPUs (cores)"
    description: "You can customize the number of CPU cores to a flexible shape."
    visible:
      and:
        - eq:
            - appdbsrv_shape
            - "VM.Standard.E3.Flex"
  appdbsrv_ram:
    type: integer
    minimum: 1
    maximum: 1024
    required: true
    title: "App / DB memory (GB)"
    description: "You can customize the amount of memory allocated to a flexible shape."
    visible:
      and:
        - eq:
            - appdbsrv_shape
            - "VM.Standard.E3.Flex"
  env_name:
    type: string
    title: "Environment Name"
    description: "Name for the environment - e.g. fn4 - lower case and digits only - must start with lower case letter"
    pattern: "^[a-z][a-z0-9]+$"
    default: "fn4"
    required: true
  specify_prefix:
    title: "Would you like to specify a prefix for the deployment?"
    type: boolean
    default: false
  name_prefix:
    type: string
    title: "Display/Host Name Prefix"
    description: "Optional prefix for all Display Names and Hostnames - lower case and digits only - must start with lower case letter"
    pattern: "^[a-z][a-z0-9]+$"
    visible: ${specify_prefix}
  appdb_boot_size:
    type: integer
    title: "App/DB Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  appdb_backup_size:
    type: integer
    title: "App/DB Server Backup Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  create_child_comp:
    title: "Create a child compartment for the stack"
    type: boolean
    default: true
  install_certs:
    title: "Install fn4dev.ml certificates?"
    type: boolean
    default: true
  create_dns:
    title: "Create DNS record in oci.fn4dev.ml?"
    type: boolean
    default: true
  show_testing_others:
    title: "Display all other settings / testing options?"
    type: boolean
    default: false
  bastion_boot_size:
    type: integer
    title: "Bastion Server Boot Volume Size"
    description: "Size in GB.  Size must be between 50 GB and 32,768 GB (32 TB)."
    minimum: 50
    maximum: 32768
  deploy_test:
    visible: false
outputs:
  Fn4_bastion:
    title: "Bastion DNS / Public IP Address"
    type: copyableString
    visible: true
  Fn4App_DB_SrvPrivateIP:
    title: "App/DB Private IP Address"
    type: copyableString
    visible: true
  Fn4_deploy_id:
    title: "Deployment ID"
    type: string
    visible: true
