#cloud-config

write_files:
# setup scripts
  - path: "/root/bootstrap_root.sh"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${bootstrap_root_sh_content}
  # - path: "/tmp/bootstrap_ubuntu.sh"
  #   permissions: "0777"
  #   encoding: "gzip+base64"
  #   content: |
  #     ${bootstrap_ubuntu_sh_content}
  - path: "/tmp/stack_info.json"
    permissions: "0777"
    encoding: "gzip+base64"
    content: |
      ${stack_info_content}
  # - path: "/tmp/install_Fn4.sh"
  #   permissions: "0777"
  #   encoding: "gzip+base64"
  #   content: |
  #     ${install_Fn4_sh_content}
  # - path: "/tmp/inject_pub_keys.sh"
  #   permissions: "0777"
  #   encoding: "gzip+base64"
  #   content: |
  #     ${inject_pub_keys_sh_content}
  # - path: "/tmp/install_nginx.sh"
  #   permissions: "0777"
  #   encoding: "gzip+base64"
  #   content: |
  #     ${install_nginx_sh_content}

runcmd:
 - echo "Running root script..."
 - /root/bootstrap_root.sh
 - echo "Finished root script."
#  - echo "Set permissions on scripts to run as ubuntu user."
#  - chown ubuntu:ubuntu /tmp/bootstrap_ubuntu.sh /tmp/stack_info.json /tmp/install_Fn4.sh /tmp/inject_pub_keys.sh
#  - echo "Running ubuntu user script..."
#  - sudo -i -H -u ubuntu bash /tmp/bootstrap_ubuntu.sh
#  - echo "Finished ubuntu user script."
 - echo "Move stack_info.json..."
 - mv /tmp/stack_info.json /home/ubuntu/stack_info.json
#  - echo "Running inject pub keys script..."
#  - sudo -i -H -u ubuntu bash /tmp/inject_pub_keys.sh
#  - echo "Running install_nginx certs..."
#  - sudo -i -H -u ubuntu bash /tmp/install_nginx.sh
#  - echo "Running install Fn4 script..."
#  - sudo -i -H -u ubuntu bash /tmp/install_Fn4.sh
 - echo "Finished Fn4 install script."
 

final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /root/cloud-init.log'}